<a href="https://colab.research.google.com/github/almeda-sj07/LinearAlgebra-58013/blob/main/DeterminantofMatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np

A = np.array([[4,7,8],[-9,0,0],[2,3,4]])
print("Array A:\n",A)

#determinant function in linear algebra library
print("Determinant =",round(np.linalg.det(A)))

Array A:
 [[ 4  7  8]
 [-9  0  0]
 [ 2  3  4]]
Determinant = 36


In [18]:
B = np.array([[2,3,-5],[7,1,-2],[-3,4,1]])
print("Array B:\n",B)
print("Determinant =",round(np.linalg.det(B)))

Array B:
 [[ 2  3 -5]
 [ 7  1 -2]
 [-3  4  1]]
Determinant = -140


Exercise:

In [19]:
A = np.array([[1,2,-1],[4,6,-2],[-1,3,3]])
print("Array A:\n",A)
print("Determinant =",round(np.linalg.det(A)))

Array A:
 [[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]]
Determinant = -14


In [23]:
#Basket method
# A = [
#    1 2 -1 | 1 2
#    4 6 -2 | 4 6
#    -1 3 3 | -1 3
#]


detA = ((1*6*3)+(2*-2*-1)+(-1*4*3)) - ((-1*6*-1)+(3*-2*1)+(3*4*2))
print("Determinant =",detA)

Determinant = -14
