<a href="https://colab.research.google.com/github/almeda-sj07/LinearAlgebra-58013/blob/main/LongQuiz1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1. Consider the four matrices, A = [1,2,3,4,5,6], B = [1,2,3,4,5,6], C = [1,2,3,4,5,6,7,8,9], D = [1,2,3,4]

In [50]:
import numpy as np

A = np.array([
    [1,2,3],
    [4,5,6]
])

B = np.array([
    [1,2],
    [3,4],
    [5,6]
])

C = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]

])

D = np.array([
    [1,2],
    [3,4]
])

print("array A:\n",A)
print("array B:\n",B)
print("array C:\n",C)
print("array D:\n",D)

array A:
 [[1 2 3]
 [4 5 6]]
array B:
 [[1 2]
 [3 4]
 [5 6]]
array C:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array D:
 [[1 2]
 [3 4]]


a. AB

In [54]:
dp = np.dot(A,B)
dp

array([[22, 28],
       [49, 64]])

b. D + D

In [55]:
sum = np.add(D,D)
sum

array([[2, 4],
       [6, 8]])

c. 2C

In [56]:
prod = np.multiply(2,C)
prod

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

Problem 2. Find the cross-product of matrices, A = [2,7,4] and B. = [3,9,8]. Show your solutions using Python program.

In [57]:
A = np.array([2,7,4])
B = np.array([3,9,8])

cp = np.cross(A,B)
cp

array([20, -4, -3])

In [58]:
# A = 2i + 7j + 4k
# B = 3i + 9j + 8k

x_cp = (A[1]*B[2]-B[1]*A[2])
y_cp = (A[2]*B[0]-A[0]*B[2])
z_cp = (A[0]*B[1]-A[1]*B[0])

print("The cross product of A and B is [",x_cp,",",y_cp,",",z_cp,"].")

The cross product of A and B is [ 20 , -4 , -3 ].
