<a href="https://colab.research.google.com/github/almeda-sj07/LinearAlgebra-58013/blob/main/PythonExercise9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [77]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

A = np.array([
    [1,4],
    [0,3]
])
np.linalg.det(A)

3.0000000000000004

In [78]:
## Now other mathematics classes would require you to solve this by hand,
## and that is great for practicing your memorization and coordination skills
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
np.linalg.det(B)

-235.0000000000002

Coding Activity 9

In [79]:
A = np.array([
    [8,4,5],
    [9,10,23],
    [0,9,10]
])

B = np.array([
    [1,1,1],
    [1,2,2],
    [1,2,3]
])

#Commutative Property of Matrix Multiplication: AB ≠ BA
AB = np.dot(A,B)
BA = np.dot(B,A)

t_value = np.equal(AB,BA)

print("Product of A & B:\n",AB,"\nProduct of B & A:\n",BA)
print("\nTruth value of AB & BA:\n",t_value)
print("Therefore, AB is not equal to BA.")

Product of A & B:
 [[17 26 31]
 [42 75 98]
 [19 38 48]] 
Product of B & A:
 [[17 23 38]
 [26 42 71]
 [26 51 81]]

Truth value of AB & BA:
 [[ True False False]
 [False False False]
 [False False False]]
Therefore, AB is not equal to BA.


In [80]:
#Associative Property of Matrix Multiplication: (AB)C = A(BC)

C = np.array([
    [1,0,0],
    [1,1,0],
    [1,1,1]
])

BC = np.dot(B,C)
AB_C = np.dot(AB,C)
A_BC = np.dot(A,BC)

t_value = np.equal(AB_C,A_BC)

print("Product of AB & C:\n",AB_C,"\nProduct of A & BC:\n",A_BC)
print("\nTruth value of (AB)C & A(BC):\n",t_value)
print("Therefore, (AB)C is equal to A(BC).")

Product of AB & C:
 [[ 74  57  31]
 [215 173  98]
 [105  86  48]] 
Product of A & BC:
 [[ 74  57  31]
 [215 173  98]
 [105  86  48]]

Truth value of (AB)C & A(BC):
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
Therefore, (AB)C is equal to A(BC).


In [81]:
#Distributive Property of Matrix Multiplication: A(B+C) = AB + AC

add_BC = np.add(B,C)
A_add_BC = np.dot(A,add_BC)

AC = np.dot(A,C)
total = np.add(AB,AC)

t_value = np.equal(A_add_BC,total)

print("Product of A(B+C):\n",A_add_BC,"\nSum of AB & AC:\n",total)
print("\nTruth value of A(B+C) & AB + AC:\n",t_value)
print("Therefore, A(B+C) is equal to AB + AC.")

Product of A(B+C):
 [[ 34  35  36]
 [ 84 108 121]
 [ 38  57  58]] 
Sum of AB & AC:
 [[ 34  35  36]
 [ 84 108 121]
 [ 38  57  58]]

Truth value of A(B+C) & AB + AC:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
Therefore, A(B+C) is equal to AB + AC.


In [82]:
#Multiplicative Identity Property: IA = A; AI = A

I = 1
IA = np.dot(I,A)
AI = np.dot(A,I)

t_value1 = np.equal(A,IA)
t_value2 = np.equal(A,AI)
t_value3 = np.equal(IA,AI)

print("Array A:\n",A,"\nProduct of I & A:\n",IA,"\nProoduct of A & I:\n",AI)
print("\nTruth value of A & IA:\n",t_value1)
print("Truth value of A & AI:\n",t_value2)
print("Truth value of IA & AI:\n",t_value3)
print("Therefore, IA = AI = A")

Array A:
 [[ 8  4  5]
 [ 9 10 23]
 [ 0  9 10]] 
Product of I & A:
 [[ 8  4  5]
 [ 9 10 23]
 [ 0  9 10]] 
Prooduct of A & I:
 [[ 8  4  5]
 [ 9 10 23]
 [ 0  9 10]]

Truth value of A & IA:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
Truth value of A & AI:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
Truth value of IA & AI:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
Therefore, IA = AI = A


In [83]:
#Multiplicative Property of Zero: OA = O; AO = O

O = 0
OA = np.dot(O,A)
AO = np.dot(A,O)

t_value = np.equal(OA,AO)

print("O =",O,"\nProduct of O & A:\n",OA,"\nProduct of A & O:\n",AO)
print("\nTruth value of OA & AO:\n",t_value)
print("Therefore, OA = AO = O.")

O = 0 
Product of O & A:
 [[0 0 0]
 [0 0 0]
 [0 0 0]] 
Product of A & O:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

Truth value of OA & AO:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
Therefore, OA = AO = O.


In [84]:
#Dimension Property: (m x n)*(n x k) = (m x k)

D = np.array([
    [1,2],
    [2,3],
    [3,4]
])

E = np.array([
    [1,1,2],
    [2,2,3]
])

sD = np.shape(D) #(m x n)
sE = np.shape(E) #(n x k)
DE = np.dot(D,E)
sDE = np.shape(DE) #(m x k)

print("Shape of array D:",sD,"\nShape of array E:",sE)
print("Product of D & E:\n",DE,"\nShape of DE:",sDE)
print("Therefore, (m x n)*(n x k) = (m x k).")

Shape of array D: (3, 2) 
Shape of array E: (2, 3)
Product of D & E:
 [[ 5  5  8]
 [ 8  8 13]
 [11 11 18]] 
Shape of DE: (3, 3)
Therefore, (m x n)*(n x k) = (m x k).
