<a href="https://colab.research.google.com/github/almeda-sj07/LinearAlgebra-58013/blob/main/PythonExercise10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import numpy as np

X = np.array([
    [1,1,1],
    [3,-2,-1],
    [-1,4,2]
], dtype=float)
Y = np.array([
    [1],
    [4],
    [-3]
],dtype=float)
print(X)
print(X.shape)
print(Y)
print(Y.shape)

[[ 1.  1.  1.]
 [ 3. -2. -1.]
 [-1.  4.  2.]]
(3, 3)
[[ 1.]
 [ 4.]
 [-3.]]
(3, 1)


Coding Activity 10

In [45]:
B = np.array([
    [30,10,120],
    [40,20,200],
    [50,40,360]
])

C = np.array([
    [12500],
    [18000],
    [25700]
])

#Cramer's Rule
B1 = np.array([
    [12500,10,120],
    [18000,20,200],
    [25700,40,360]
])

B2 = np.array([
    [30,12500,120],
    [40,18000,200],
    [50,25700,360]
])

B3 = np.array([
    [30,10,12500],
    [40,20,18000],
    [50,40,25700]
])

dB = round(np.linalg.det(B))
dB1 = round(np.linalg.det(B1))
dB2 = round(np.linalg.det(B2))
dB3 = round(np.linalg.det(B3))

F = float(dB1/dB)
Y = float(dB2/dB)
E = float(dB3/dB)

print("Determinants:\nB:",dB,"\nB1:",dB1,"\nB2:",dB2,"\nB3:",dB3)
print("\nPrice of flour per sack:",F,"pesos.")
print("Price of yeast per pack:",Y,"pesos.")
print("Price of one piece of egg:",E,"pesos.")

Determinants:
B: 4000 
B1: 1320000 
B2: 560000 
B3: 40000

Price of flour per sack: 330.0 pesos.
Price of yeast per pack: 140.0 pesos.
Price of one piece of egg: 10.0 pesos.
