<a href="https://colab.research.google.com/github/almeda-sj07/LinearAlgebra-58013/blob/main/PythonExercise3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Vector Operations**

Vector Addition

In [1]:
import numpy as np
A = np.array([1,2,0])
B = np.array([3,1,-2])
C = np.array([0,0,1])

A + B + C

array([ 4,  3, -1])

In [2]:
np.add(A,np.add(B,C))

array([ 4,  3, -1])

In [3]:
np.sum(B)

2

Vector Subtraction

In [4]:
np.subtract(A,B)

array([-2,  1,  2])

In [5]:
A-B

array([-2,  1,  2])

Vector Multiplication

In [6]:
np.multiply(A,B)

array([3, 2, 0])

In [7]:
A * B

array([3, 2, 0])

Vector Division

In [8]:
np.divide(A,B)

array([ 0.33333333,  2.        , -0.        ])

In [9]:
A / B

array([ 0.33333333,  2.        , -0.        ])

In [10]:
C = np.array([3.9,1.8,7.7])
D = np.array([1,1,1])
C / D

array([3.9, 1.8, 7.7])

In [11]:
np.array(A / B, dtype = int)

array([0, 2, 0])