<a href="https://colab.research.google.com/github/almeda-sj07/LinearAlgebra-58013/blob/main/PythonExercise4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
A = np.array([[-0.4],[4.3],[-0.6]])
B = np.array([-0.2,0.2,1])
C = np.array([-0.2,2.1,-1.5])

Vector Operations

In [11]:
#Addition
sum = A + B + C
print("The sum of the arrays is:\n",sum)

#Subtraction
diff = A - B - C
print("The difference of the arrays is:\n",diff)

#Multiplication
prod = A * B * C
print("The product of the arrays is:\n",prod)

#Division
quot = A / B / C
print("The quotient of the arrays is:\n",quot)

The sum of the arrays is:
 [[-0.8  1.9 -0.9]
 [ 3.9  6.6  3.8]
 [-1.   1.7 -1.1]]
The difference of the arrays is:
 [[ 0.  -2.7  0.1]
 [ 4.7  2.   4.8]
 [-0.2 -2.9 -0.1]]
The product of the arrays is:
 [[-0.016 -0.168  0.6  ]
 [ 0.172  1.806 -6.45 ]
 [-0.024 -0.252  0.9  ]]
The quotient of the arrays is:
 [[-10.          -0.95238095   0.26666667]
 [107.5         10.23809524  -2.86666667]
 [-15.          -1.42857143   0.4       ]]
