<a href="https://colab.research.google.com/github/almeda-sj07/LinearAlgebra-58013/blob/main/Vectors%2CSpaces%2C%26Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Vectors

In [ ]:
import numpy as np

A = np.array([4,3])
B = np.array([2,-5])

print('Vector A is ', A)
print('Vector B is ', B)

Vector A is  [4 3]
Vector B is  [ 2 -5]


Shape of the Matrices

In [ ]:
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])
ball = np.array([ball1,ball2])

print(ball1)
print(ball2,'\n')
print('arrays:\n',ball,'\n')

[1 2 3]
[ 0  1 -1] 

arrays:
 [[ 1  2  3]
 [ 0  1 -1]] 



In [ ]:
sball1 = np.shape(ball1)    #Shape
sball2 = np.shape(ball2)
sball = sball1 + sball2

print(sball)

(3, 3)


In [ ]:
dball1 = np.ndim(ball1)    #Dimension
dball2 = np.ndim(ball2)
dball = (dball1,dball2)

print(dball)

(1, 1)


Vector Operations

In [ ]:
a = np.array([4,3])
b = np.array([2,-5])

aR = np.add(a,b)        #Addition
print(aR)

[ 6 -2]


In [ ]:
sR = np.subtract(a,b)   #Subtraction
print(sR)

[2 8]


In [ ]:
mR = np.multiply(a,b)   #Multiplication
print(mR)

[  8 -15]


In [ ]:
dR = np.divide(a,b)     #Division
print(dR)

[ 2.  -0.6]


In [ ]:
s = np.array([2])

spR1 = np.multiply(s,a)   #Scalar Product
spR2 = np.multiply(s,b)

print(spR1)
print(spR2)

[8 6]
[  4 -10]


In [ ]:
dpR = np.dot(a,b)       #Dot Product
print(dpR)

-7


In [ ]:
cpR = np.cross(a,b)     #Cross Product
print(cpR)

-26


Property of Matrix

In [ ]:
c = np.eye(2,2)         #Identity Matrix
print(c)

[[1. 0.]
 [0. 1.]]


In [ ]:
d = np.zeros([5,5])     #Zero Matrix
print(d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
e = np.full([3,3],7)    #Full Matrix
print(e)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [132]:
f = np.transpose(a)      #Transpose Matrix
print(f)

[4 3]


In [ ]:
g = np.empty([0,0])       #Empty Matrix
print(g)

[]
